BOROUGH_COMMUNITY_PROFILES = {
    "Barking and Dagenham": {
        "religion": "Christian majority with significant Muslim communities",
        "food": "Halal butchers, local supermarkets, multicultural eateries",
        "shops": "Town centres and retail parks",
        "schools": "Mixed school performance",
        "vibe": "Working-class, family-oriented",
    },
    "Barnet": {
        "religion": "Large Jewish community alongside Christian and Muslim populations",
        "food": "Kosher food shops, international grocers",
        "shops": "Town centres and shopping parades",
        "schools": "Strong overall school performance",
        "vibe": "Suburban, family-focused",
    },
    "Bexley": {
        "religion": "Predominantly Christian and secular",
        "food": "Supermarkets and local eateries",
        "shops": "Suburban shopping areas",
        "schools": "Generally good schools",
        "vibe": "Quiet, suburban, residential",
    },
    "Brent": {
        "religion": "Large Hindu, Muslim, and Christian communities",
        "food": "South Asian grocers, halal shops, ethnic restaurants",
        "shops": "Local high streets and shopping centres",
        "schools": "Wide mix of school quality",
        "vibe": "Suburban, diverse, family-oriented",
    },
    "Bromley": {
        "religion": "Predominantly Christian and secular",
        "food": "Supermarkets, cafés, and local restaurants",
        "shops": "Town centres and suburban high streets",
        "schools": "Generally strong schools",
        "vibe": "Green, suburban, family-friendly",
    },
    "Camden": {
        "religion": "Predominantly Christian and secular with diverse minority faiths",
        "food": "Independent cafés, international restaurants, organic food shops",
        "shops": "High streets, markets, and central retail areas",
        "schools": "Generally strong school performance",
        "vibe": "Young, urban, walkable, cultural",
    },
    "Croydon": {
        "religion": "Christian majority with significant Muslim and Hindu communities",
        "food": "Halal food shops, Caribbean and South Asian restaurants",
        "shops": "Major town centre and retail complexes",
        "schools": "Mixed school performance",
        "vibe": "Busy, mixed urban-suburban",
    },
    "Ealing": {
        "religion": "Christian majority with Hindu, Muslim, and Sikh communities",
        "food": "Indian, Persian, and international food shops and restaurants",
        "shops": "Town centres and suburban shopping parades",
        "schools": "Generally strong schools",
        "vibe": "Leafy, suburban, family-friendly",
    },
    "Enfield": {
        "religion": "Christian majority with Muslim and Jewish communities",
        "food": "Halal and kosher food shops alongside supermarkets",
        "shops": "Town centres and suburban retail",
        "schools": "Mixed school performance",
        "vibe": "Suburban, residential",
    },
    "Greenwich": {
        "religion": "Christian majority with Muslim and other minority faiths",
        "food": "International restaurants, supermarkets, cafés",
        "shops": "Town centres and riverside retail",
        "schools": "Mixed to good schools",
        "vibe": "Historic, family-friendly, mixed density",
    },
    "Hackney": {
        "religion": "Christian majority with Jewish and Muslim communities",
        "food": "Organic food shops, halal grocers, global cuisine",
        "shops": "Independent retailers and busy high streets",
        "schools": "Mixed school quality",
        "vibe": "Creative, diverse, community-focused",
    },
    "Hammersmith and Fulham": {
        "religion": "Christian and secular majority with diverse minorities",
        "food": "International cuisine, cafés, specialist food shops",
        "shops": "Town centres and local high streets",
        "schools": "Good school availability",
        "vibe": "Well-connected, residential",
    },
    "Haringey": {
        "religion": "Christian majority with Muslim and Jewish communities",
        "food": "Ethnic food shops and international restaurants",
        "shops": "Busy high streets",
        "schools": "Mixed school quality",
        "vibe": "Urban, diverse",
    },
    "Harrow": {
        "religion": "Large Hindu and Christian communities with Muslim minorities",
        "food": "South Asian food shops and supermarkets",
        "shops": "Town centres and suburban high streets",
        "schools": "Strong academic reputation",
        "vibe": "Quiet, suburban, family-focused",
    },
    "Havering": {
        "religion": "Predominantly Christian and secular",
        "food": "Supermarkets and traditional high street shops",
        "shops": "Town centres and retail parks",
        "schools": "Generally good schools",
        "vibe": "Suburban, car-oriented",
    },
    "Hillingdon": {
        "religion": "Christian majority with Muslim, Sikh, and Hindu communities",
        "food": "Local supermarkets and ethnic food shops",
        "shops": "Suburban shopping centres",
        "schools": "Mixed school performance",
        "vibe": "Car-friendly, suburban",
    },
    "Hounslow": {
        "religion": "Christian majority with large Hindu, Sikh, and Muslim populations",
        "food": "South Asian grocers, halal shops, international dining",
        "shops": "Town centres and retail parks",
        "schools": "Mixed school performance",
        "vibe": "Suburban, diverse",
    },
    "Islington": {
        "religion": "Predominantly Christian and secular with diverse minorities",
        "food": "Independent cafés, international restaurants, food markets",
        "shops": "Vibrant high streets and local shopping areas",
        "schools": "Good range of schools",
        "vibe": "Trendy, walkable, community-focused",
    },
    "Kensington and Chelsea": {
        "religion": "Christian and secular with global religious representation",
        "food": "High-end supermarkets, international fine dining",
        "shops": "Luxury and central retail areas",
        "schools": "Limited but high-performing schools",
        "vibe": "Affluent, central, international",
    },
    "Kingston upon Thames": {
        "religion": "Christian majority with minority faiths",
        "food": "Supermarkets, cafés, international restaurants",
        "shops": "Major town centre retail",
        "schools": "Good school performance",
        "vibe": "Suburban, lively town centre",
    },
    "Lambeth": {
        "religion": "Christian majority with Muslim and Afro-Caribbean communities",
        "food": "Caribbean, African, and international food shops",
        "shops": "Busy high streets and local centres",
        "schools": "Mixed to good schools",
        "vibe": "Lively, diverse",
    },
    "Lewisham": {
        "religion": "Christian majority with Muslim communities",
        "food": "Ethnic food shops, markets, international cuisine",
        "shops": "Town centres and local high streets",
        "schools": "Mixed school quality",
        "vibe": "Urban, diverse, improving",
    },
    "Merton": {
        "religion": "Christian majority with Hindu and Muslim minorities",
        "food": "Local supermarkets and international food shops",
        "shops": "Town centres and high streets",
        "schools": "Generally good schools",
        "vibe": "Residential, family-friendly",
    },
    "Newham": {
        "religion": "Highly diverse with Muslim, Christian, Hindu, and Sikh communities",
        "food": "Halal butchers, South Asian food shops, multicultural restaurants",
        "shops": "Town centres and retail parks",
        "schools": "Large number of schools, mixed performance",
        "vibe": "Dense, multicultural, family-focused",
    },
    "Redbridge": {
        "religion": "Large Muslim, Hindu, and Christian communities",
        "food": "South Asian grocers, halal food shops",
        "shops": "Town centres and local high streets",
        "schools": "Generally strong schools",
        "vibe": "Suburban, diverse",
    },
    "Richmond upon Thames": {
        "religion": "Predominantly Christian and secular",
        "food": "Independent cafés, organic food shops",
        "shops": "Town centres and boutique shopping",
        "schools": "Strong school performance",
        "vibe": "Affluent, green, family-friendly",
    },
    "Southwark": {
        "religion": "Christian and secular majority with Muslim communities",
        "food": "Wide variety of supermarkets, cafés, international restaurants",
        "shops": "Major town centres and local high streets",
        "schools": "Generally good school availability",
        "vibe": "Urban, mixed residential",
    },
    "Sutton": {
        "religion": "Predominantly Christian and secular",
        "food": "Supermarkets and local dining",
        "shops": "Town centre and suburban retail",
        "schools": "Strong grammar and secondary schools",
        "vibe": "Quiet, suburban, family-oriented",
    },
    "Tower Hamlets": {
        "religion": "Predominantly Muslim alongside Christian and secular communities",
        "food": "Halal grocers, Bangladeshi and Middle Eastern restaurants, markets",
        "shops": "Local high streets, markets, independent retailers",
        "schools": "High density of schools, mixed Ofsted ratings",
        "vibe": "Urban, family-oriented, culturally vibrant",
    },
    "Waltham Forest": {
        "religion": "Christian majority with Muslim communities",
        "food": "Ethnic food shops and cafés",
        "shops": "Local high streets and town centres",
        "schools": "Mixed to good schools",
        "vibe": "Community-focused, improving walkability",
    },
    "Wandsworth": {
        "religion": "Predominantly Christian and secular",
        "food": "Supermarkets, cafés, family-oriented dining",
        "shops": "Town centres and suburban shopping streets",
        "schools": "Generally strong schools",
        "vibe": "Family-friendly, residential",
    },
    "Westminster": {
        "religion": "Christian and secular with all major religions represented",
        "food": "International dining, premium grocery stores",
        "shops": "Major retail streets and central shopping districts",
        "schools": "Limited residential schools",
        "vibe": "Central, commercial, highly walkable",
    },
}
