BOROUGH_TRANSPORT_PROFILES = {
    "Camden": "Dense Tube and rail coverage, extensive bus network, very high walkability, strong cycling infrastructure, frequent school streets and controlled traffic zones.",
    "Westminster": "Exceptional Tube and bus connectivity, walkable central area, heavy congestion charging and traffic restrictions, limited car access in many streets.",
    "Islington": "Good Tube and Overground access, strong bus routes, high walkability, cycling corridors, common school streets and low-traffic neighbourhoods.",
    "Hackney": "Overground-dominated with limited Tube coverage, strong bus network, excellent cycling infrastructure, high walkability, widespread low-traffic neighbourhoods.",
    "Tower Hamlets": "Excellent Tube, DLR, and Overground access, very walkable urban environment, strong cycling routes, congestion charge areas nearby.",
    "Greenwich": "DLR, rail, and bus connectivity, some Tube access in the north, moderate walkability, cycling routes along the Thames, school streets present.",
    "Lewisham": "Strong rail and Overground links, limited Tube access, bus-reliant areas, moderate walkability, longer commute times to Central London.",
    "Southwark": "Good Tube and rail coverage, high walkability in central areas, strong bus network, congestion charging zones nearby, extensive cycling routes.",
    "Lambeth": "Excellent Tube and rail access, strong bus coverage, walkable neighbourhoods, good cycling infrastructure, frequent school streets.",
    "Wandsworth": "Rail-dominated transport with limited Tube coverage, good bus links, variable walkability, popular for cycling along river routes.",
    "Hammersmith and Fulham": "Strong Tube coverage, frequent bus services, high walkability, good cycling infrastructure, controlled parking zones common.",
    "Kensington and Chelsea": "Excellent Tube and bus connectivity, very walkable central streets, heavy parking and traffic restrictions, congestion charging nearby.",
    "Brent": "Good Tube and rail access in parts, strong bus network, mixed walkability, car use common in outer areas.",
    "Ealing": "Strong Tube and rail links, good bus coverage, moderate walkability, car-friendly residential areas in outer zones.",
    "Hounslow": "Tube and rail access with Heathrow links, bus-reliant areas, moderate walkability, car use common.",
    "Harrow": "Rail and Tube access in town centres, bus-dependent residential areas, lower walkability, car-friendly.",
    "Hillingdon": "Limited Tube access outside town centres, strong bus reliance, low walkability in outer areas, car-oriented borough.",
    "Richmond upon Thames": "Rail and Tube access, good bus links, high walkability in town centres, strong cycling routes, limited congestion.",
    "Kingston upon Thames": "Rail-focused transport, limited Tube access, good bus coverage, moderate walkability, car use common.",
    "Merton": "Northern Line access in parts, strong rail links, bus-reliant areas, moderate walkability.",
    "Sutton": "Rail-based transport, limited Tube access, longer commute times, lower walkability, car-friendly borough.",
    "Croydon": "Tram, rail, and bus hub, longer commute times to Central London, mixed walkability, car-friendly outer areas.",
    "Bromley": "Rail-dominated transport, no Tube access, longer commute times, low walkability in suburban areas, car-oriented.",
    "Bexley": "Rail-based transport, limited public transport density, long commutes, low walkability, car-dependent.",
    "Havering": "Rail access with sparse bus coverage, long commute times, low walkability, car-dominated borough.",
    "Redbridge": "Central Line access in parts, strong bus coverage, moderate walkability, suburban car use common.",
    "Newham": "Excellent Tube, DLR, and rail connectivity, high walkability in regeneration areas, strong cycling infrastructure.",
    "Barking and Dagenham": "District Line and rail access, bus-reliant areas, lower walkability, car-friendly.",
    "Waltham Forest": "Victoria Line and Overground access, strong cycling infrastructure, improving walkability, widespread low-traffic neighbourhoods.",
    "Enfield": "Rail and limited Tube access, bus-reliant residential areas, lower walkability, car use common.",
    "Barnet": "Northern Line and rail access, strong bus routes, moderate walkability, suburban car use.",
    "Haringey": "Victoria Line and rail access, strong bus network, moderate walkability, cycling infrastructure improving.",
    "City of London": "Exceptional public transport density, minimal residential use, extremely walkable, heavy traffic restrictions and congestion charging."
}
